<?php echo $this->doctype() ?>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart Application</title>
  <?php echo $this->headLink()->appendStylesheet('/css/default.css') ?>
</head>
<body>
<div id="header">
    <div id="header-logo" style="float: left">
        <b>ZF Quickstart Application</b>
    </div>
    <div id="header-navigation" style="float: right">
        <a href="<?php echo $this->url(
            array('controller'=>'index'),
            'default',
            true) ?>">Guestbook</a>
    </div>
</div>
<section id="navigation">
    <ul>
        <li>
            <a href="/index/index">Index</a>
        </li>
        <li>
            <a href="/index/sign">Sign Guestbook</a>
        </li>
    </ul>
</section>